name: app_mental_health_care
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_riverpod: ^3.0.3
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  flutter_dotenv: ^6.0.0
  vapi: ^0.1.0
  permission_handler: ^11.4.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - .env
